model:
  target: segmentation_models_pytorch.Unet
  params:
    encoder_name: efficientnet-b2
    encoder_weights: null
    in_channels: 1
    classes: 20
    activation: null

optimizer:
  target: torch.optim.Adam
  learning_rate: 3e-4
  weight_decay: 3e-5
  max_epoch: 100
  max_iter: -1
  warmup_iter: -1
  lr_scheduler: lambda

saliency_balancing_fusion:
  usage: true
  grid_size: 8

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    train:
      target: dataloaders.NEW_BrainDataset.get_training
      params:
        location_scale: true
        modality:
          - t1
        tile_z_dim: 1
    validation:
      target: dataloaders.NEW_BrainDataset.get_validation
      params:
        modality:
          - dwi
        tile_z_dim: 1
    test:
      target: dataloaders.NEW_BrainDataset.get_test
      params:
        modality:
          - dwi
        tile_z_dim: 1